from src.controllers.CatchController import CatchController
from src.controllers.CannonController import CannonController
from src.controllers.FireballController import FireballController

(CatchController,CannonController,FireballController)